# Generated by Django 3.1.5 on 2021-01-19 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('mic', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='mic code')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('cash_balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=254)),
                ('figi', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('stock_type', models.CharField(max_length=100, verbose_name='type')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('units', models.PositiveIntegerField()),
                ('cost_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stocks.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='stocks.currencypair')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
