# Generated by Django 3.1.5 on 2021-01-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_sell', models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('date', models.DateField()),
                ('fee', models.DecimalField(decimal_places=4, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.stock')),
            ],
        ),
    ]
